<a href="https://colab.research.google.com/github/Lzino/TIL_Today-I-Learned/blob/master/Pytorch_deeplearningzerotoall_part1_basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reference
* https://www.edwith.org/boostcourse-dl-pytorch/
* https://github.com/deeplearningzerotoall/PyTorch

# Lab 1: Tensor Manipulation

## Numpy

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## Pytorch

In [6]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [7]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [8]:
print(t[0], t[1], t[-1]) # Element
print(t[1:5], t[4:-1]) # slicing
print(t[:3], t[2:])

tensor(0.) tensor(1.) tensor(6.)
tensor([1., 2., 3., 4.]) tensor([4., 5.])
tensor([0., 1., 2.]) tensor([2., 3., 4., 5., 6.])


In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])
print(t)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])


In [11]:
print(t.dim())
print(t.size())

4
torch.Size([1, 2, 3, 4])


In [12]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ',m1.shape)
print('Shape of Matrix 2: ',m2.shape)
print(m1.matmul(m2))

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [14]:
## Broadcasting

# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [15]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [17]:
# Mean
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [18]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try :
  print(t.mean())
except Exception as exc:
  print(exc)
  print('error')


Can only calculate the mean of floating types. Got Long instead.
error


In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [21]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [22]:
# view : reshape
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [23]:
# squeeze : dimension reduction
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [24]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [25]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


In [26]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


In [27]:
# Scatter : onehotencoding
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [28]:
one_hot = torch.zeros(4,3) # batch 4 / classes 3
one_hot.scatter_(1,lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [30]:
print(torch.cat([x,y], dim = 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [31]:
print(torch.cat([x,y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [32]:
# stacking
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [33]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [34]:
# stacking = same that
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [35]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [36]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [38]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [39]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [40]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [41]:
 # _는 기존에 메모리에 계산을 해주는 역할. 분산 처리에 필요함
 # 속도도 더 빠름. 가비지 컬렉터 없이 작동하기때문에 
print(x.mul_(2.)) 
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# Lab 2: Linear Regression

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [43]:
# For reproducibility
torch.manual_seed(1)

In [44]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [45]:
print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [46]:
#  requires_grad= True 는 학습 명시
W = torch.zeros(1, requires_grad= True)
print(W)

tensor([0.], requires_grad=True)


In [47]:
b = torch.zeros(1, requires_grad= True)
print(b)

tensor([0.], requires_grad=True)


In [48]:
# Hypothesis
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [49]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [50]:
print(hypothesis - y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [51]:
print(hypothesis - y_train ** 2)

tensor([[-1.],
        [-4.],
        [-9.]], grad_fn=<SubBackward0>)


In [52]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [53]:
# Gradient Descent
optimizer = optim.SGD([W, b], lr=0.01)

In [54]:
optimizer.zero_grad() # gradient 초기화
cost.backward() # gradient 계산
optimizer.step() # update

In [55]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [56]:
hy = x_train * W + b
print(hy)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [57]:
cost = torch.mean((hy - y_train) ** 2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


### Linear Regression Modeling without Optim

In [58]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1)
# learning rate 설정
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W
    
    # cost gradient 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    gradient = torch.sum((W * x_train - y_train) * x_train)

    print('Epoch {:4d}/{} W: {:.3f}, Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), cost.item()
    ))

    # cost gradient로 H(x) 개선
    W -= lr * gradient

Epoch    0/10 W: 0.000, Cost: 4.666667
Epoch    1/10 W: 1.400, Cost: 0.746666
Epoch    2/10 W: 0.840, Cost: 0.119467
Epoch    3/10 W: 1.064, Cost: 0.019115
Epoch    4/10 W: 0.974, Cost: 0.003058
Epoch    5/10 W: 1.010, Cost: 0.000489
Epoch    6/10 W: 0.996, Cost: 0.000078
Epoch    7/10 W: 1.002, Cost: 0.000013
Epoch    8/10 W: 0.999, Cost: 0.000002
Epoch    9/10 W: 1.000, Cost: 0.000000
Epoch   10/10 W: 1.000, Cost: 0.000000


### Linear Regression Modeling with Optim

In [59]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 500
for epoch in range(1,nb_epochs + 1):

  hy = x_train * W + b 

  loss = torch.mean((hy - y_train) ** 2)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 50 == 0 :
    print(f'Epoch {epoch} / {nb_epochs} , W : {W.item() :.3f}, b : {b.item() :.3f}, Loss : {loss.item() :.5f} ')

Epoch 50 / 500 , W : 0.854, b : 0.326, Loss : 0.01544 
Epoch 100 / 500 , W : 0.873, b : 0.290, Loss : 0.01210 
Epoch 150 / 500 , W : 0.887, b : 0.257, Loss : 0.00951 
Epoch 200 / 500 , W : 0.900, b : 0.228, Loss : 0.00748 
Epoch 250 / 500 , W : 0.911, b : 0.202, Loss : 0.00588 
Epoch 300 / 500 , W : 0.921, b : 0.179, Loss : 0.00462 
Epoch 350 / 500 , W : 0.930, b : 0.159, Loss : 0.00363 
Epoch 400 / 500 , W : 0.938, b : 0.141, Loss : 0.00286 
Epoch 450 / 500 , W : 0.945, b : 0.125, Loss : 0.00224 
Epoch 500 / 500 , W : 0.951, b : 0.111, Loss : 0.00176 


### Linear Regression Model with nn.Moudule

In [60]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1) # input 차원 , output 차원

  def forward(self, x):
    return self.linear(x)

In [61]:
model = LinearRegressionModel()

In [62]:
hy2 = model(x_train)
print(hy2)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


In [63]:
print(hy2)
print(y_train)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)
tensor([[1.],
        [2.],
        [3.]])


In [64]:
loss2 = F.mse_loss(hy2, y_train)
print(loss2) 

tensor(2.1471, grad_fn=<MseLossBackward>)


In [65]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)
optimizer.zero_grad()
loss2.backward()
optimizer.step()

In [66]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

Epoch    0/1000 W: -0.101, b: 0.508 Cost: 4.630286
Epoch  100/1000 W: 0.713, b: 0.653 Cost: 0.061555
Epoch  200/1000 W: 0.774, b: 0.514 Cost: 0.038037
Epoch  300/1000 W: 0.822, b: 0.404 Cost: 0.023505
Epoch  400/1000 W: 0.860, b: 0.317 Cost: 0.014525
Epoch  500/1000 W: 0.890, b: 0.250 Cost: 0.008975
Epoch  600/1000 W: 0.914, b: 0.196 Cost: 0.005546
Epoch  700/1000 W: 0.932, b: 0.154 Cost: 0.003427
Epoch  800/1000 W: 0.947, b: 0.121 Cost: 0.002118
Epoch  900/1000 W: 0.958, b: 0.095 Cost: 0.001309
Epoch 1000/1000 W: 0.967, b: 0.075 Cost: 0.000809


# Lab 4-1: Multivariate Linear Regression

In [67]:
# For reproducibility
torch.manual_seed(1)

In [68]:
# 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [69]:
# init
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  hy3 = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  loss3 = torch.mean((hy3 - y_train) ** 2)

  optimizer.zero_grad()
  loss3.backward()
  optimizer.step()

  if epoch % 100 == 0 :
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w3.item(), w3.item(), b.item(), loss3.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.297 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.676 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.677 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.677 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.678 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.678 w3: 0.678 b: 0.009 Cost: 1.319497
Epoch  600/1000 w1: 0.699 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.266215
Epoch  700/1000 w1: 0.704 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.079390


In [70]:
# Matrix Data Representation

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [71]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [72]:
# ?????

W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 
    hypothesis = x_train.matmul(W) + b 

    # cost
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371071
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

### Multivariate Linear Regression with nn.Module

In [73]:
# 설명 듣기
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

In [74]:
class MultiLRModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

In [75]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [76]:
model = MultiLRModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs +1):
  pred = model(x_train)
  
  cost = F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print(f'Epoch {epoch :4d} / {nb_epochs}, Cost : {cost.item():6f}')

Epoch    0 / 20, Cost : 31667.593750
Epoch    1 / 20, Cost : 9926.266602
Epoch    2 / 20, Cost : 3111.513672
Epoch    3 / 20, Cost : 975.451477
Epoch    4 / 20, Cost : 305.908630
Epoch    5 / 20, Cost : 96.042679
Epoch    6 / 20, Cost : 30.260782
Epoch    7 / 20, Cost : 9.641681
Epoch    8 / 20, Cost : 3.178685
Epoch    9 / 20, Cost : 1.152871
Epoch   10 / 20, Cost : 0.517862
Epoch   11 / 20, Cost : 0.318802
Epoch   12 / 20, Cost : 0.256388
Epoch   13 / 20, Cost : 0.236810
Epoch   14 / 20, Cost : 0.230660
Epoch   15 / 20, Cost : 0.228719
Epoch   16 / 20, Cost : 0.228095
Epoch   17 / 20, Cost : 0.227880
Epoch   18 / 20, Cost : 0.227799
Epoch   19 / 20, Cost : 0.227759
Epoch   20 / 20, Cost : 0.227732


### Load data

In [77]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [78]:
!ls 'drive/My Drive/Colab Notebooks/GitHub/TIL/'

 data-01-test-score.csv
 data-02-stock_daily.csv
 data-03-diabetes.csv
 data-04-zoo.csv
'Fraud-detection with Autoencoder.ipynb'
 GAN_tutorial.ipynb
'제목 없는 그림.gdraw'
 Generative_model_tutorial.ipynb
 pytorch_AAE.ipynb
 Pytorch_deeplearningzerotoall_part1_basic_ML.ipynb
 torch_tutorial_nn.ipynb
'Variational autoencoder.ipynb'


In [79]:
path1 = 'drive/My Drive/Colab Notebooks/GitHub/TIL/'

In [80]:
xy = np.loadtxt(path1 + 'data-01-test-score.csv', delimiter= ',', dtype= np.float32)

In [81]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [82]:
print('x_data.shape: ', x_data.shape)
print(x_data[:5])

x_data.shape:  (25, 3)
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [83]:
print('y_data.shape: ', y_data.shape)
print(y_data[:5])

y_data.shape:  (25, 1)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [84]:
# For reproducibility
torch.manual_seed(1)

In [85]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [86]:
model = MultiLRModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print(f'Epoch {epoch :4d} / {nb_epochs}, Cost : {cost.item():6f}')

Epoch    0 / 20, Cost : 28693.490234
Epoch    1 / 20, Cost : 10618.750000
Epoch    2 / 20, Cost : 3936.014893
Epoch    3 / 20, Cost : 1465.219482
Epoch    4 / 20, Cost : 551.693726
Epoch    5 / 20, Cost : 213.934647
Epoch    6 / 20, Cost : 89.052269
Epoch    7 / 20, Cost : 42.876007
Epoch    8 / 20, Cost : 25.799641
Epoch    9 / 20, Cost : 19.482420
Epoch   10 / 20, Cost : 17.143093
Epoch   11 / 20, Cost : 16.274509
Epoch   12 / 20, Cost : 15.949720
Epoch   13 / 20, Cost : 15.825985
Epoch   14 / 20, Cost : 15.776565
Epoch   15 / 20, Cost : 15.754661
Epoch   16 / 20, Cost : 15.742919
Epoch   17 / 20, Cost : 15.734919
Epoch   18 / 20, Cost : 15.728307
Epoch   19 / 20, Cost : 15.722219
Epoch   20 / 20, Cost : 15.716355


# Lab 5: Logistic Classification

In [87]:
torch.manual_seed(2)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [88]:
W = torch.zeros((2, 1), requires_grad= True)
b = torch.zeros(1, requires_grad= True)

In [89]:
# logistic regression

lo_re = 1 / (1+ torch.exp(-x_train.matmul(W) + b))

In [90]:
print(lo_re)
print(lo_re.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [91]:
loss_lo = -(y_train * torch.log(lo_re) +(1 - y_train) * torch.log(1- lo_re))

In [92]:
print(loss_lo)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [93]:
loss = loss_lo.mean()
print(loss)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [94]:
F.binary_cross_entropy(lo_re, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [95]:
# 설명 필요
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    return self.sigmoid(self.linear(x))

In [96]:
model = BinaryClassifier()

In [97]:
# Model
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  hy = torch.sigmoid(x_train.matmul(W) + b)
  hy2 = model(x_train)

  cost = -(y_train * torch.log(hy) + (1 - y_train) * torch.log(1 - hy)).mean()
  cost2 = F.binary_cross_entropy(hy, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0 :
    print(f'Epoch {epoch :4d} / {nb_epochs}, Cost : {cost.item():6f}')

Epoch    0 / 1000, Cost : 0.693147
Epoch  100 / 1000, Cost : 0.414327
Epoch  200 / 1000, Cost : 0.349521
Epoch  300 / 1000, Cost : 0.301302
Epoch  400 / 1000, Cost : 0.263532
Epoch  500 / 1000, Cost : 0.233518
Epoch  600 / 1000, Cost : 0.209313
Epoch  700 / 1000, Cost : 0.189496
Epoch  800 / 1000, Cost : 0.173035
Epoch  900 / 1000, Cost : 0.159179
Epoch 1000 / 1000, Cost : 0.147375


# Lab 6-1: Softmax Classification


## Cross Entropy Loss (Low-level)

In [98]:
z = torch.FloatTensor([1, 2, 3])
hy = F.softmax(z, dim = 0)
print(hy)
print(hy.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [99]:
z = torch.rand(3, 5 , requires_grad= True)
hy = F.softmax(z, dim = 1) # ?
print("z: ", z)
print("hy: ", hy)

z:  tensor([[0.4745, 0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332, 0.3901],
        [0.9088, 0.5334, 0.7073, 0.7116, 0.2050]], requires_grad=True)
hy:  tensor([[0.1969, 0.2501, 0.2275, 0.1907, 0.1348],
        [0.2354, 0.1349, 0.2243, 0.2171, 0.1882],
        [0.2618, 0.1798, 0.2140, 0.2149, 0.1295]], grad_fn=<SoftmaxBackward>)


In [100]:
y = torch.randint(5, (3,)).long() # class = 5 / sample = 3
print(y)

tensor([1, 0, 0])


In [101]:
y_onehot = torch.zeros_like(hy)
print("onehot 1 : ", y_onehot)
y_onehot_s = y_onehot.scatter_(1, y.unsqueeze(1) , 1) # inplace. ( dim , size ,  what number)
print("onehot scatter : ", y_onehot_s)

onehot 1 :  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
onehot scatter :  tensor([[0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])


In [102]:
cost = (y_onehot * - torch.log(hy)).sum(dim =1).mean()
print("cost : ", cost)

cost :  tensor(1.3908, grad_fn=<MeanBackward0>)


In [103]:
# Low level
torch.log(F.softmax(z, dim = 1))

tensor([[-1.6251, -1.3860, -1.4805, -1.6570, -2.0038],
        [-1.4463, -2.0031, -1.4947, -1.5272, -1.6704],
        [-1.3403, -1.7158, -1.5418, -1.5375, -2.0441]], grad_fn=<LogBackward>)

In [104]:
# High level
F.log_softmax(z, dim=1)

tensor([[-1.6251, -1.3860, -1.4805, -1.6570, -2.0038],
        [-1.4463, -2.0031, -1.4947, -1.5272, -1.6704],
        [-1.3403, -1.7158, -1.5418, -1.5375, -2.0441]],
       grad_fn=<LogSoftmaxBackward>)

### NLL loss
* F.log_softmax() + F.nll_loss() = F.cross_entropy()

In [105]:
# Low level
(y_onehot * - torch.log(F.softmax(z, dim= 1))).sum(dim = 1).mean()

tensor(1.3908, grad_fn=<MeanBackward0>)

In [106]:
# High level
F.nll_loss(F.log_softmax(z, dim= 1), y)

tensor(1.3908, grad_fn=<NllLossBackward>)

In [107]:
F.cross_entropy(z,y)

tensor(1.3908, grad_fn=<NllLossBackward>)

### Training with Low-level Cross Entropy Loss

In [108]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [109]:
class SoftmaxClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(4, 3)

  def forward(self, x):
    return self.linear(x)

In [110]:
model = SoftmaxClassifier()

In [111]:
# 모델 초기화
W = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.1)


nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  # Low level
  hy = F.softmax(x_train.matmul(W) + b, dim = 1)
  y_one_hot = torch.zeros_like(hy)
  #print('y_one_hot[0] : ', y_one_hot[0])
  y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
  #print('y_one_hot2[0] : ', y_one_hot[0])
  
  # High level
  z = x_train.matmul(W) + b

  # nn.Module
  pred = model(x_train)

  cost = (y_one_hot * - torch.log(F.softmax(hy, dim = 1))).sum(dim = 1).mean()
  cost2 = F.cross_entropy(z, y_train)
  cost3 = F.cross_entropy(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0 :
    print(f'Epoch {epoch :4d} / {nb_epochs}, Cost : {cost.item():6f}')

Epoch    0 / 1000, Cost : 1.098612
Epoch  100 / 1000, Cost : 0.901535
Epoch  200 / 1000, Cost : 0.839114
Epoch  300 / 1000, Cost : 0.807826
Epoch  400 / 1000, Cost : 0.788472
Epoch  500 / 1000, Cost : 0.774822
Epoch  600 / 1000, Cost : 0.764449
Epoch  700 / 1000, Cost : 0.756191
Epoch  800 / 1000, Cost : 0.749398
Epoch  900 / 1000, Cost : 0.743671
Epoch 1000 / 1000, Cost : 0.738749


# Lab 6-2: Fancy Softmax Classification

In [112]:
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1)
y = torch.randint(5, (3,)).long()
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

### softmax

In [113]:
#Low level
torch.log(F.softmax(z, dim = 1))

tensor([[-1.3022, -1.7139, -1.6327, -1.7961, -1.6790],
        [-2.1615, -1.4849, -1.5038, -1.5989, -1.4527],
        [-1.5211, -1.7109, -1.6800, -1.6948, -1.4662]], grad_fn=<LogBackward>)

In [114]:
#High level
F.log_softmax(z, dim = 1)

tensor([[-1.3022, -1.7139, -1.6327, -1.7961, -1.6790],
        [-2.1615, -1.4849, -1.5038, -1.5989, -1.4527],
        [-1.5211, -1.7109, -1.6800, -1.6948, -1.4662]],
       grad_fn=<LogSoftmaxBackward>)

### cross entropy

In [115]:
# Low level
(y_one_hot * -torch.log(F.softmax(z, dim = 1))).sum(dim = 1).mean()

tensor(1.6104, grad_fn=<MeanBackward0>)

In [116]:
# High level
F.nll_loss(F.log_softmax(z, dim = 1), y.long())

tensor(1.6104, grad_fn=<NllLossBackward>)

In [117]:
F.cross_entropy(z,y)

tensor(1.6104, grad_fn=<NllLossBackward>)

In [121]:
path1 = 'drive/My Drive/Colab Notebooks/GitHub/TIL/'

In [122]:
xy = np.loadtxt(path1 + 'data-04-zoo.csv', delimiter= ',', dtype= np.float32)

In [133]:
x_train = torch.FloatTensor(xy[:, 0:-1])
y_train = torch.LongTensor(xy[:, [-1]]).squeeze()

In [127]:
print('x_train.shape', x_train.shape)
print('x_train[0] : ',x_train[0:2])

x_train.shape torch.Size([101, 16])
x_train[0] :  tensor([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 4., 1., 0., 1.]])


In [126]:
print('y_train.shape',y_train.shape)
print('y_train[0] : ',y_train[0:2])

y_train.shape torch.Size([101])
y_train[0] :  tensor([0., 0.])


In [134]:
nb_classes = 7
y_one_hot = torch.zeros((len(y_train), nb_classes))
y_one_hot = y_one_hot.scatter(1, y_train.unsqueeze(1), 1)

In [135]:
class SoftmaxClassifierModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(16,7)

  def forward(self, x):
    return self.linear(x)

In [136]:
model = SoftmaxClassifierModel()

In [137]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)

  cost = F.cross_entropy(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0 :
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 1.812718
Epoch  100/1000 Cost: 0.448549
Epoch  200/1000 Cost: 0.306761
Epoch  300/1000 Cost: 0.239133
Epoch  400/1000 Cost: 0.197463
Epoch  500/1000 Cost: 0.168735
Epoch  600/1000 Cost: 0.147555
Epoch  700/1000 Cost: 0.131214
Epoch  800/1000 Cost: 0.118185
Epoch  900/1000 Cost: 0.107535
Epoch 1000/1000 Cost: 0.098658
